services:
  ros1:
    image: ${ROS_IMAGE:-osrf/ros:noetic-desktop-full}
    container_name: vop2el_ros1
    network_mode: host
    environment:
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_IP=127.0.0.1
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /home/tejas/project_workspaces/personal_github/volp2el_ws:/volp2el_ws:rw
      - /home/tejas/project_workspaces/datasets:/datasets:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    working_dir: /volp2el_ws
    stdin_open: true
    tty: true
    command: bash
